// @ts-ignore `.open-next/worker.js` is generated by the OpenNext Cloudflare build.
import { default as openNextWorker } from './.open-next/worker.js';
import { scheduled as runScheduledTelegramSignalMonitor } from './src/server/chart-service/cloudflare-scheduled.ts';

export default {
  fetch: openNextWorker.fetch,
  scheduled: runScheduledTelegramSignalMonitor,
};

// @ts-ignore `.open-next/worker.js` is generated by the OpenNext Cloudflare build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
