export const INDICATOR_CATALOG = [
  { id: 'rsi', label: 'RSI', desc: 'Relative Strength Index', panel: 'sub' },
  { id: 'macd', label: 'MACD', desc: 'Moving Avg Convergence Div', panel: 'sub' },
  { id: 'dmi', label: 'DMI / ADX', desc: 'Directional Movement Index', panel: 'sub' },
  { id: 'stochF', label: 'Stochastic Fast', desc: 'Fast Stochastic Oscillator', panel: 'sub' },
  { id: 'stochS', label: 'Stochastic Slow', desc: 'Slow Stochastic Oscillator', panel: 'sub' },
  { id: 'cci', label: 'CCI', desc: 'Commodity Channel Index', panel: 'sub' },
  { id: 'obv', label: 'OBV', desc: 'On Balance Volume', panel: 'sub' },
  { id: 'cvd', label: 'CVD', desc: 'Cumulative Volume Delta', panel: 'sub' },
  { id: 'volume', label: 'Volume', desc: 'Trading Volume', panel: 'sub' },
  { id: 'bb', label: 'Bollinger Band', desc: 'Bollinger Bands (20,2)', panel: 'main' },
  { id: 'ma', label: 'MA', desc: 'Moving Average lines (MA1, MA2, ...)', panel: 'main' },
  { id: 'ema', label: 'EMA', desc: 'Exponential Moving Average lines (EMA1, EMA2, ...)', panel: 'main' },
  { id: 'vwap', label: 'VWAP', desc: 'Volume Weighted Avg Price', panel: 'main' },
  { id: 'supertrend', label: 'Supertrend', desc: 'ATR trend indicator', panel: 'main' },
  { id: 'statisticalTrailingStop', label: 'Statistical Trailing Stop', desc: 'Log-normal volatility trailing stop', panel: 'main' },
  { id: 'zeroLagMaTrendLevels', label: 'Zero-Lag MA Trend Levels', desc: 'Zero-lag EMA trend and ATR levels', panel: 'main' },
  { id: 'volumeProfile', label: 'Volume Profile', desc: 'Visible Range Volume Profile', panel: 'main' },
  { id: 'vpvr', label: 'Volume Profile Visible Range', desc: 'VPVR (alias of Visible Range Volume Profile)', panel: 'main' },
  { id: 'ichimoku', label: 'Ichimoku Cloud', desc: 'Ichimoku Kinko Hyo', panel: 'main' },
  { id: 'envelope', label: 'Envelope', desc: 'Price Envelope (MA ± %)', panel: 'main' },
] as const;
