export type DatabaseColumn = {
  type: string;
  nullable?: boolean;
  default?: string;
  primaryKey?: boolean;
  references?: string;
  check?: string;
};

export type DatabaseTable = {
  name: string;
  columns: Record<string, DatabaseColumn>;
  primaryKey?: string[];
  indexes?: Array<{
    name: string;
    columns: string[];
    unique?: boolean;
  }>;
};

export function getChartServiceDatabaseTables(): DatabaseTable[] {
  return [
    {
      name: 'users',
      columns: {
        id: { type: 'text', primaryKey: true },
        email: { type: 'text' },
        name: { type: 'text' },
        password_hash: { type: 'text', nullable: true },
        role: { type: 'text', check: "role in ('guest', 'member', 'trial', 'subscriber', 'salesperson', 'admin', 'super_admin')" },
        account_status: {
          type: 'text',
          default: "'active'",
          check: "account_status in ('active', 'suspended')",
        },
        phone_number: { type: 'text', nullable: true },
        profile_image_data_url: { type: 'text', nullable: true },
        referral_code: { type: 'text' },
        referred_by_user_id: { type: 'text', nullable: true, references: 'users.id' },
        created_at: { type: 'timestamptz', default: 'now()' },
        email_verified_at: { type: 'timestamptz', nullable: true },
      },
      indexes: [
        { name: 'idx_users_email', columns: ['email'] },
        { name: 'idx_users_role', columns: ['role'] },
        { name: 'idx_users_referral_code', columns: ['referral_code'] },
        { name: 'idx_users_referred_by_user_id', columns: ['referred_by_user_id'] },
      ],
    },
    {
      name: 'auth_sessions',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        created_at: { type: 'timestamptz' },
        expires_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_auth_sessions_user_id', columns: ['user_id'] },
        { name: 'idx_auth_sessions_expires_at', columns: ['expires_at'] },
      ],
    },
    {
      name: 'push_subscriptions',
      columns: {
        endpoint: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        p256dh: { type: 'text' },
        auth: { type: 'text' },
        expiration_time: { type: 'numeric', nullable: true },
        user_agent: { type: 'text', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_push_subscriptions_user_id', columns: ['user_id'] },
        { name: 'idx_push_subscriptions_updated_at', columns: ['updated_at'] },
      ],
    },
    {
      name: 'social_auth_accounts',
      columns: {
        id: { type: 'text', primaryKey: true },
        provider: { type: 'text', check: "provider in ('google', 'naver', 'kakao')" },
        provider_user_id: { type: 'text' },
        user_id: { type: 'text', references: 'users.id' },
        email: { type: 'text' },
        created_at: { type: 'timestamptz' },
        updated_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_social_auth_accounts_provider_user', columns: ['provider', 'provider_user_id'], unique: true },
        { name: 'idx_social_auth_accounts_user_id', columns: ['user_id'] },
      ],
    },
    {
      name: 'password_reset_tokens',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        token_hash: { type: 'text' },
        created_at: { type: 'timestamptz' },
        expires_at: { type: 'timestamptz' },
        used_at: { type: 'timestamptz', nullable: true },
      },
      indexes: [
        { name: 'idx_password_reset_tokens_token_hash', columns: ['token_hash'] },
        { name: 'idx_password_reset_tokens_user_id', columns: ['user_id'] },
      ],
    },
    {
      name: 'email_verification_tokens',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        token_hash: { type: 'text' },
        created_at: { type: 'timestamptz' },
        expires_at: { type: 'timestamptz' },
        used_at: { type: 'timestamptz', nullable: true },
      },
      indexes: [
        { name: 'idx_email_verification_tokens_token_hash', columns: ['token_hash'] },
        { name: 'idx_email_verification_tokens_user_id', columns: ['user_id'] },
      ],
    },
    {
      name: 'subscription_plans',
      columns: {
        id: { type: 'text', primaryKey: true },
        name: { type: 'text' },
        duration_days: { type: 'integer' },
        base_price_usd: { type: 'numeric(12,2)' },
        discount_percent: { type: 'numeric(5,2)' },
        is_active: { type: 'boolean', default: 'true' },
      },
    },
    {
      name: 'subscriptions',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        plan_id: { type: 'text', nullable: true, references: 'subscription_plans.id' },
        status: { type: 'text' },
        starts_at: { type: 'timestamptz', nullable: true },
        ends_at: { type: 'timestamptz', nullable: true },
        approved_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        approved_at: { type: 'timestamptz', nullable: true },
        cancelled_at: { type: 'timestamptz', nullable: true },
        refunded_at: { type: 'timestamptz', nullable: true },
        created_at: { type: 'timestamptz' },
        updated_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_subscriptions_user_id', columns: ['user_id'] },
        { name: 'idx_subscriptions_status', columns: ['status'] },
      ],
    },
    {
      name: 'public_board_posts',
      columns: {
        id: { type: 'text', primaryKey: true },
        category: {
          type: 'text',
          check: "category in ('notice', 'qna', 'faq')",
        },
        title: { type: 'text' },
        body: { type: 'text' },
        is_published: { type: 'boolean', default: 'true' },
        sort_order: { type: 'integer', default: '0' },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
      },
      indexes: [
        { name: 'idx_public_board_posts_category', columns: ['category'] },
        { name: 'idx_public_board_posts_is_published', columns: ['is_published'] },
        { name: 'idx_public_board_posts_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'notice_popups',
      columns: {
        id: { type: 'text', primaryKey: true },
        title: { type: 'text' },
        body_html: { type: 'text' },
        is_active: { type: 'boolean', default: 'true' },
        sort_order: { type: 'integer', default: '0' },
        start_at: { type: 'timestamptz', nullable: true },
        end_at: { type: 'timestamptz', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
      },
      indexes: [
        { name: 'idx_notice_popups_is_active', columns: ['is_active'] },
        { name: 'idx_notice_popups_start_at', columns: ['start_at'] },
        { name: 'idx_notice_popups_end_at', columns: ['end_at'] },
        { name: 'idx_notice_popups_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'support_threads',
      columns: {
        id: { type: 'text', primaryKey: true },
        author_user_id: { type: 'text', references: 'users.id' },
        category: { type: 'text' },
        title: { type: 'text' },
        visibility: { type: 'text' },
        status: { type: 'text' },
        created_at: { type: 'timestamptz' },
        updated_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_support_threads_author_user_id', columns: ['author_user_id'] },
        { name: 'idx_support_threads_status', columns: ['status'] },
      ],
    },
    {
      name: 'support_messages',
      columns: {
        id: { type: 'text', primaryKey: true },
        thread_id: { type: 'text', references: 'support_threads.id' },
        author_user_id: { type: 'text', references: 'users.id' },
        body: { type: 'text' },
        is_admin_reply: { type: 'boolean', default: 'false' },
        created_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_support_messages_thread_id', columns: ['thread_id'] },
        { name: 'idx_support_messages_author_user_id', columns: ['author_user_id'] },
      ],
    },
    {
      name: 'payment_requests',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        plan_id: { type: 'text', references: 'subscription_plans.id' },
        subscription_id: { type: 'text', references: 'subscriptions.id' },
        support_thread_id: { type: 'text', nullable: true, references: 'support_threads.id' },
        method: { type: 'text' },
        amount_usd: { type: 'numeric(12,2)' },
        amount_krw: { type: 'integer', nullable: true },
        exchange_rate: { type: 'numeric(12,4)', nullable: true },
        referral_points_used: { type: 'numeric(12,2)', default: '0' },
        status: { type: 'text' },
        depositor_name: { type: 'text', nullable: true },
        transaction_id: { type: 'text', nullable: true },
        transaction_verification_status: {
          type: 'text',
          default: "'unchecked'",
          check: "transaction_verification_status in ('unchecked', 'verified', 'mismatch', 'failed')",
        },
        transaction_verification_message: { type: 'text', nullable: true },
        transaction_verified_at: { type: 'timestamptz', nullable: true },
        admin_note: { type: 'text', nullable: true },
        confirmed_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        confirmed_at: { type: 'timestamptz', nullable: true },
        created_at: { type: 'timestamptz' },
        updated_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_payment_requests_user_id', columns: ['user_id'] },
        { name: 'idx_payment_requests_status', columns: ['status'] },
        { name: 'idx_payment_requests_subscription_id', columns: ['subscription_id'] },
        { name: 'idx_payment_requests_support_thread_id', columns: ['support_thread_id'] },
      ],
    },
    {
      name: 'referral_ledgers',
      columns: {
        id: { type: 'text', primaryKey: true },
        referrer_user_id: { type: 'text', references: 'users.id' },
        referred_user_id: { type: 'text', references: 'users.id' },
        payment_request_id: { type: 'text', references: 'payment_requests.id' },
        amount_usd: { type: 'numeric(12,2)' },
        percent: { type: 'numeric(5,2)' },
        points: { type: 'numeric(12,2)' },
        status: { type: 'text' },
        confirm_after: { type: 'timestamptz' },
        confirmed_at: { type: 'timestamptz', nullable: true },
        reversed_at: { type: 'timestamptz', nullable: true },
        created_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_referral_ledgers_referrer_user_id', columns: ['referrer_user_id'] },
        { name: 'idx_referral_ledgers_referred_user_id', columns: ['referred_user_id'] },
        { name: 'idx_referral_ledgers_payment_request_id', columns: ['payment_request_id'] },
      ],
    },
    {
      name: 'referral_program_settings',
      columns: {
        id: { type: 'text', primaryKey: true },
        subscriber_cashback_percent: {
          type: 'numeric(5,2)',
          default: '3',
          check: 'subscriber_cashback_percent >= 0 and subscriber_cashback_percent <= 100',
        },
        reward_percent: {
          type: 'numeric(5,2)',
          default: '10',
          check: 'reward_percent >= 0 and reward_percent <= 100',
        },
        salesperson_reward_percent: {
          type: 'numeric(5,2)',
          default: '30',
          check: 'salesperson_reward_percent >= 0 and salesperson_reward_percent <= 100',
        },
        sales_team_reward_percent: {
          type: 'numeric(5,2)',
          default: '50',
          check: 'sales_team_reward_percent >= 0 and sales_team_reward_percent <= 100',
        },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
    },
    {
      name: 'sales_teams',
      columns: {
        id: { type: 'text', primaryKey: true },
        name: { type: 'text' },
        commission_percent: {
          type: 'numeric(5,2)',
          default: '30',
          check: 'commission_percent >= 0 and commission_percent <= 100',
        },
        salesperson_ids: { type: 'jsonb', default: "'[]'::jsonb" },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
      },
      indexes: [
        { name: 'idx_sales_teams_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'free_trial_policy_settings',
      columns: {
        id: { type: 'text', primaryKey: true },
        base_duration_days: {
          type: 'integer',
          default: '7',
          check: 'base_duration_days > 0 and base_duration_days <= 365',
        },
        event_enabled: { type: 'boolean', default: 'false' },
        event_starts_at: { type: 'timestamptz', nullable: true },
        event_ends_at: { type: 'timestamptz', nullable: true },
        event_duration_days: {
          type: 'integer',
          nullable: true,
          check: 'event_duration_days is null or (event_duration_days > 0 and event_duration_days <= 365)',
        },
        event_allow_reapply: { type: 'boolean', default: 'false' },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_free_trial_policy_settings_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'free_trial_user_allowances',
      columns: {
        user_id: { type: 'text', primaryKey: true, references: 'users.id' },
        remaining_count: {
          type: 'integer',
          default: '0',
          check: 'remaining_count >= 0 and remaining_count <= 999',
        },
        note: { type: 'text', nullable: true },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_free_trial_user_allowances_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'free_trial_usage_records',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        subscription_id: { type: 'text', references: 'subscriptions.id' },
        source: {
          type: 'text',
          check: "source in ('standard', 'global_event', 'user_allowance')",
        },
        started_at: { type: 'timestamptz' },
        ends_at: { type: 'timestamptz' },
        duration_days: { type: 'integer' },
        policy_snapshot_json: { type: 'jsonb', default: "'{}'::jsonb" },
        created_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_free_trial_usage_records_user_id', columns: ['user_id'] },
        { name: 'idx_free_trial_usage_records_subscription_id', columns: ['subscription_id'] },
        { name: 'idx_free_trial_usage_records_created_at', columns: ['created_at'] },
      ],
    },
    {
      name: 'payment_transfer_settings',
      columns: {
        id: { type: 'text', primaryKey: true },
        bank_name: { type: 'text' },
        bank_account_number: { type: 'text' },
        bank_account_holder: { type: 'text' },
        bank_logo_url: { type: 'text' },
        usdt_address: { type: 'text' },
        usdt_network: { type: 'text' },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_payment_transfer_settings_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'web_info_settings',
      columns: {
        id: { type: 'text', primaryKey: true },
        terms_content: { type: 'text' },
        privacy_content: { type: 'text' },
        plan_services_json: { type: 'jsonb', default: "'{}'::jsonb" },
        updated_by_admin_id: { type: 'text', nullable: true, references: 'users.id' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_web_info_settings_updated_by_admin_id', columns: ['updated_by_admin_id'] },
      ],
    },
    {
      name: 'chart_user_settings',
      columns: {
        user_id: { type: 'text', primaryKey: true, references: 'users.id' },
        settings_json: { type: 'jsonb', default: "'{}'::jsonb" },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
    },
    {
      name: 'signal_admin_settings',
      columns: {
        id: { type: 'text', primaryKey: true },
        hidden_symbols_json: { type: 'jsonb', default: "'[]'::jsonb" },
        disabled_symbols_json: { type: 'jsonb', default: "'[]'::jsonb" },
        hidden_strategy_ids_json: { type: 'jsonb', default: "'[]'::jsonb" },
        global_signal_policy_json: { type: 'jsonb', default: "'{}'::jsonb" },
        symbol_signal_policies_json: { type: 'jsonb', default: "'[]'::jsonb" },
        strategy_param_profiles_json: { type: 'jsonb', default: "'[]'::jsonb" },
        strategy_mgmt_visible: { type: 'boolean', default: 'false' },
        selected_strategy_id: { type: 'text', default: "'strategy_js_grid_martingale'" },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
    },
    {
      name: 'telegram_bot_profiles',
      columns: {
        id: { type: 'text', primaryKey: true },
        name: { type: 'text' },
        bot_token: { type: 'text' },
        chat_id: { type: 'text' },
        is_enabled: { type: 'boolean', default: 'true' },
          event_types_json: { type: 'jsonb', default: "'[]'::jsonb" },
          strategy_ids_json: { type: 'jsonb', default: "'[]'::jsonb" },
          symbol_ids_json: { type: 'jsonb', default: "'[]'::jsonb" },
          timeframe_ids_json: { type: 'jsonb', default: "'[]'::jsonb" },
          last_tested_at: { type: 'timestamptz', nullable: true },
        last_test_status: {
          type: 'text',
          nullable: true,
          check: "last_test_status is null or last_test_status in ('success', 'failed')",
        },
        last_test_error: { type: 'text', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_telegram_bot_profiles_is_enabled', columns: ['is_enabled'] },
        { name: 'idx_telegram_bot_profiles_updated_at', columns: ['updated_at'] },
      ],
    },
    {
      name: 'telegram_delivery_logs',
      columns: {
        id: { type: 'text', primaryKey: true },
        profile_id: { type: 'text', references: 'telegram_bot_profiles.id' },
        event_type: {
          type: 'text',
          check: "event_type in ('buy', 'sell', 'stop_loss', 'take_profit')",
        },
        strategy_id: { type: 'text' },
        symbol_id: { type: 'text' },
        message: { type: 'text' },
        status: {
          type: 'text',
          check: "status in ('sent', 'failed')",
        },
        telegram_message_id: { type: 'text', nullable: true },
        error_message: { type: 'text', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_telegram_delivery_logs_profile_id', columns: ['profile_id'] },
        { name: 'idx_telegram_delivery_logs_created_at', columns: ['created_at'] },
        { name: 'idx_telegram_delivery_logs_symbol_id', columns: ['symbol_id'] },
      ],
    },
    {
      name: 'telegram_signal_watch_states',
      columns: {
        key: { type: 'text', primaryKey: true },
        strategy_id: { type: 'text' },
        symbol_id: { type: 'text' },
        timeframe: { type: 'text' },
        last_checked_candle_time: { type: 'bigint', default: '0' },
        last_signal_candle_time: { type: 'bigint', nullable: true },
        last_signal_event_type: {
          type: 'text',
          nullable: true,
          check: "last_signal_event_type is null or last_signal_event_type in ('buy', 'sell', 'stop_loss', 'take_profit')",
        },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_telegram_signal_watch_states_updated_at', columns: ['updated_at'] },
        { name: 'idx_telegram_signal_watch_states_symbol', columns: ['symbol_id', 'timeframe'] },
      ],
    },
    {
      name: 'signup_agreements',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        terms_accepted_at: { type: 'timestamptz' },
        privacy_accepted_at: { type: 'timestamptz' },
        terms_content: { type: 'text' },
        privacy_content: { type: 'text' },
        terms_settings_updated_at: { type: 'timestamptz' },
        privacy_settings_updated_at: { type: 'timestamptz' },
        ip_address: { type: 'text', nullable: true },
        user_agent: { type: 'text', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_signup_agreements_user_id', columns: ['user_id'] },
        { name: 'idx_signup_agreements_created_at', columns: ['created_at'] },
      ],
    },
    {
      name: 'market_candles',
      columns: {
        market: { type: 'text' },
        symbol: { type: 'text' },
        timeframe: { type: 'text' },
        time: { type: 'timestamptz' },
        open: { type: 'numeric' },
        high: { type: 'numeric' },
        low: { type: 'numeric' },
        close: { type: 'numeric' },
        volume: { type: 'numeric', default: '0' },
        created_at: { type: 'timestamptz', default: 'now()' },
        updated_at: { type: 'timestamptz', default: 'now()' },
      },
      primaryKey: ['market', 'symbol', 'timeframe', 'time'],
      indexes: [
        { name: 'idx_market_candles_symbol_time', columns: ['market', 'symbol', 'time'] },
        { name: 'idx_market_candles_timeframe_time', columns: ['market', 'symbol', 'timeframe', 'time'] },
      ],
    },
    {
      name: 'notifications',
      columns: {
        id: { type: 'text', primaryKey: true },
        user_id: { type: 'text', references: 'users.id' },
        category: { type: 'text' },
        title: { type: 'text' },
        body: { type: 'text' },
        link_url: { type: 'text', nullable: true },
        read_at: { type: 'timestamptz', nullable: true },
        archived_at: { type: 'timestamptz', nullable: true },
        created_at: { type: 'timestamptz' },
      },
      indexes: [
        { name: 'idx_notifications_user_id_read_at', columns: ['user_id', 'read_at'] },
        { name: 'idx_notifications_user_id_archived_at', columns: ['user_id', 'archived_at'] },
      ],
    },
    {
      name: 'email_outbox',
      columns: {
        id: { type: 'text', primaryKey: true },
        sender_email: { type: 'text' },
        recipient_email: { type: 'text' },
        template: { type: 'text' },
        subject: { type: 'text' },
        body: { type: 'text' },
        status: { type: 'text', check: "status in ('queued', 'sent', 'failed')" },
        created_at: { type: 'timestamptz' },
        sent_at: { type: 'timestamptz', nullable: true },
        last_error: { type: 'text', nullable: true },
      },
      indexes: [
        { name: 'idx_email_outbox_status_created_at', columns: ['status', 'created_at'] },
      ],
    },
    {
      name: 'audit_logs',
      columns: {
        id: { type: 'bigserial', primaryKey: true },
        actor_admin_id: { type: 'text', references: 'users.id' },
        action: { type: 'text' },
        target_type: { type: 'text' },
        target_id: { type: 'text' },
        before_json: { type: 'jsonb', nullable: true },
        after_json: { type: 'jsonb', nullable: true },
        created_at: { type: 'timestamptz', default: 'now()' },
      },
      indexes: [
        { name: 'idx_audit_logs_actor_admin_id', columns: ['actor_admin_id'] },
        { name: 'idx_audit_logs_target', columns: ['target_type', 'target_id'] },
      ],
    },
  ];
}

export function renderChartServicePostgresSchema(): string {
  const statements = getChartServiceDatabaseTables().flatMap((table) => {
    const columnLines = Object.entries(table.columns).map(([name, column]) => renderColumn(name, column));
    const checks = Object.entries(table.columns)
      .filter(([, column]) => column.check)
      .map(([name, column]) => `  constraint chk_${table.name}_${name} check (${column.check})`);
    const foreignKeys = Object.entries(table.columns)
      .filter(([, column]) => column.references)
      .map(([name, column]) => {
        const [targetTable, targetColumn] = column.references!.split('.');
        return `  foreign key (${name}) references ${targetTable}(${targetColumn})`;
      });
    const compositePrimaryKey = table.primaryKey?.length
      ? [`  primary key (${table.primaryKey.join(', ')})`]
      : [];
    const tableSql = [
      `create table if not exists ${table.name} (`,
      [...columnLines, ...checks, ...foreignKeys, ...compositePrimaryKey].join(',\n'),
      ');',
    ].join('\n');
    const indexSql = (table.indexes ?? []).map((index) => (
      `create ${index.unique ? 'unique ' : ''}index if not exists ${index.name} on ${table.name} (${index.columns.join(', ')});`
    ));
    return [tableSql, ...indexSql];
  });

  return `${[...statements, ...getChartServiceSchemaUpgradeStatements()].join('\n\n')}\n`;
}

function getChartServiceSchemaUpgradeStatements(): string[] {
  return [
    'alter table if exists notifications add column if not exists archived_at timestamptz;',
    'alter table if exists market_candles enable row level security;',
    'alter table if exists payment_requests add column if not exists support_thread_id text;',
    'alter table if exists payment_requests add column if not exists transaction_id text;',
    "alter table if exists payment_requests add column if not exists transaction_verification_status text;",
    "alter table if exists payment_requests add column if not exists transaction_verification_message text;",
    'alter table if exists payment_requests add column if not exists transaction_verified_at timestamptz;',
    "update payment_requests set transaction_verification_status = 'unchecked' where transaction_verification_status is null or transaction_verification_status = '';",
    'create index if not exists idx_payment_requests_support_thread_id on payment_requests (support_thread_id);',
    'alter table if exists users add column if not exists phone_number text;',
    'alter table if exists users add column if not exists profile_image_data_url text;',
    'alter table if exists users add column if not exists referral_code text;',
    'alter table if exists users add column if not exists referred_by_user_id text;',
    'alter table if exists users add column if not exists created_at timestamptz;',
    'alter table if exists users add column if not exists email_verified_at timestamptz;',
    'alter table if exists users alter column password_hash drop not null;',
    "update users set referral_code = upper(substr(md5(id), 1, 6)) where referral_code is null or referral_code = '' or referral_code !~ '^[A-Z0-9]{6}$';",
    'update users set created_at = now() where created_at is null;',
    'create index if not exists idx_users_referral_code on users (referral_code);',
    'create index if not exists idx_users_referred_by_user_id on users (referred_by_user_id);',
    "create table if not exists social_auth_accounts (id text primary key, provider text not null, provider_user_id text not null, user_id text not null references users(id), email text not null, created_at timestamptz not null, updated_at timestamptz not null, constraint chk_social_auth_accounts_provider check (provider in ('google', 'naver', 'kakao')));",
    'delete from social_auth_accounts victim using social_auth_accounts keeper where victim.provider = keeper.provider and victim.provider_user_id = keeper.provider_user_id and (victim.updated_at < keeper.updated_at or (victim.updated_at = keeper.updated_at and victim.id < keeper.id));',
    'drop index if exists idx_social_auth_accounts_provider_user;',
    'create unique index if not exists idx_social_auth_accounts_provider_user on social_auth_accounts (provider, provider_user_id);',
    'create index if not exists idx_social_auth_accounts_user_id on social_auth_accounts (user_id);',
    'create table if not exists push_subscriptions (endpoint text primary key, user_id text not null references users(id), p256dh text not null, auth text not null, expiration_time numeric, user_agent text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());',
    'alter table if exists push_subscriptions add column if not exists user_id text;',
    'alter table if exists push_subscriptions add column if not exists p256dh text;',
    'alter table if exists push_subscriptions add column if not exists auth text;',
    'alter table if exists push_subscriptions add column if not exists expiration_time numeric;',
    'alter table if exists push_subscriptions add column if not exists user_agent text;',
    'alter table if exists push_subscriptions add column if not exists created_at timestamptz;',
    'alter table if exists push_subscriptions add column if not exists updated_at timestamptz;',
    'update push_subscriptions set created_at = now() where created_at is null;',
    'update push_subscriptions set updated_at = now() where updated_at is null;',
    'create index if not exists idx_push_subscriptions_user_id on push_subscriptions (user_id);',
    'create index if not exists idx_push_subscriptions_updated_at on push_subscriptions (updated_at);',
    'create table if not exists email_verification_tokens (id text primary key, user_id text not null references users(id), token_hash text not null, created_at timestamptz not null, expires_at timestamptz not null, used_at timestamptz);',
    'create index if not exists idx_email_verification_tokens_token_hash on email_verification_tokens (token_hash);',
    'create index if not exists idx_email_verification_tokens_user_id on email_verification_tokens (user_id);',
    'create index if not exists idx_referral_ledgers_referrer_user_id on referral_ledgers (referrer_user_id);',
    'create index if not exists idx_referral_ledgers_referred_user_id on referral_ledgers (referred_user_id);',
    'create index if not exists idx_support_messages_author_user_id on support_messages (author_user_id);',
    'alter table if exists email_outbox add column if not exists sender_email text;',
    "update email_outbox set sender_email = 'noreply@tradingcore.co' where sender_email is null or sender_email = '';",
    'alter table if exists audit_logs alter column before_json drop not null;',
    'alter table if exists audit_logs alter column after_json drop not null;',
    'create table if not exists referral_program_settings (id text primary key, subscriber_cashback_percent numeric(5,2) not null default 3, reward_percent numeric(5,2) not null default 10, salesperson_reward_percent numeric(5,2) not null default 30, sales_team_reward_percent numeric(5,2) not null default 50, updated_by_admin_id text, updated_at timestamptz not null default now());',
    'alter table if exists referral_program_settings add column if not exists subscriber_cashback_percent numeric(5,2);',
    'alter table if exists referral_program_settings add column if not exists reward_percent numeric(5,2);',
    'alter table if exists referral_program_settings add column if not exists salesperson_reward_percent numeric(5,2);',
    'alter table if exists referral_program_settings add column if not exists sales_team_reward_percent numeric(5,2);',
    'alter table if exists referral_program_settings add column if not exists updated_by_admin_id text;',
    'alter table if exists referral_program_settings add column if not exists updated_at timestamptz;',
    'update referral_program_settings set subscriber_cashback_percent = 3 where subscriber_cashback_percent is null;',
    'update referral_program_settings set reward_percent = 10 where reward_percent is null;',
    'update referral_program_settings set salesperson_reward_percent = 30 where salesperson_reward_percent is null;',
    'update referral_program_settings set sales_team_reward_percent = 50 where sales_team_reward_percent is null;',
    "insert into referral_program_settings (id, subscriber_cashback_percent, reward_percent, salesperson_reward_percent, sales_team_reward_percent, updated_at) values ('default', 3, 10, 30, 50, now()) on conflict (id) do nothing;",
    "create table if not exists sales_teams (id text primary key, name text not null, commission_percent numeric(5,2) not null default 30, salesperson_ids jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), updated_by_admin_id text);",
    'alter table if exists sales_teams add column if not exists name text;',
    'alter table if exists sales_teams add column if not exists commission_percent numeric(5,2);',
    "alter table if exists sales_teams add column if not exists salesperson_ids jsonb;",
    'alter table if exists sales_teams add column if not exists created_at timestamptz;',
    'alter table if exists sales_teams add column if not exists updated_at timestamptz;',
    'alter table if exists sales_teams add column if not exists updated_by_admin_id text;',
    "update sales_teams set salesperson_ids = '[]'::jsonb where salesperson_ids is null;",
    'create index if not exists idx_sales_teams_updated_by_admin_id on sales_teams (updated_by_admin_id);',
    'create table if not exists free_trial_policy_settings (id text primary key, base_duration_days integer not null default 7, event_enabled boolean not null default false, event_starts_at timestamptz, event_ends_at timestamptz, event_duration_days integer, event_allow_reapply boolean not null default false, updated_by_admin_id text, updated_at timestamptz not null default now());',
    'alter table if exists free_trial_policy_settings add column if not exists base_duration_days integer;',
    'alter table if exists free_trial_policy_settings add column if not exists event_enabled boolean;',
    'alter table if exists free_trial_policy_settings add column if not exists event_starts_at timestamptz;',
    'alter table if exists free_trial_policy_settings add column if not exists event_ends_at timestamptz;',
    'alter table if exists free_trial_policy_settings add column if not exists event_duration_days integer;',
    'alter table if exists free_trial_policy_settings add column if not exists event_allow_reapply boolean;',
    'alter table if exists free_trial_policy_settings add column if not exists updated_by_admin_id text;',
    'alter table if exists free_trial_policy_settings add column if not exists updated_at timestamptz;',
    'update free_trial_policy_settings set base_duration_days = 7 where base_duration_days is null;',
    'update free_trial_policy_settings set event_enabled = false where event_enabled is null;',
    'update free_trial_policy_settings set event_allow_reapply = false where event_allow_reapply is null;',
    'update free_trial_policy_settings set updated_at = now() where updated_at is null;',
    "insert into free_trial_policy_settings (id, base_duration_days, event_enabled, event_allow_reapply, updated_at) values ('default', 7, false, false, now()) on conflict (id) do nothing;",
    'create index if not exists idx_free_trial_policy_settings_updated_by_admin_id on free_trial_policy_settings (updated_by_admin_id);',
    'create table if not exists free_trial_user_allowances (user_id text primary key, remaining_count integer not null default 0, note text, updated_by_admin_id text, updated_at timestamptz not null default now());',
    'alter table if exists free_trial_user_allowances add column if not exists remaining_count integer;',
    'alter table if exists free_trial_user_allowances add column if not exists note text;',
    'alter table if exists free_trial_user_allowances add column if not exists updated_by_admin_id text;',
    'alter table if exists free_trial_user_allowances add column if not exists updated_at timestamptz;',
    'update free_trial_user_allowances set remaining_count = 0 where remaining_count is null;',
    'update free_trial_user_allowances set updated_at = now() where updated_at is null;',
    'create index if not exists idx_free_trial_user_allowances_updated_by_admin_id on free_trial_user_allowances (updated_by_admin_id);',
    "create table if not exists free_trial_usage_records (id text primary key, user_id text not null, subscription_id text not null, source text not null, started_at timestamptz not null, ends_at timestamptz not null, duration_days integer not null, policy_snapshot_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());",
    'alter table if exists free_trial_usage_records add column if not exists user_id text;',
    'alter table if exists free_trial_usage_records add column if not exists subscription_id text;',
    'alter table if exists free_trial_usage_records add column if not exists source text;',
    'alter table if exists free_trial_usage_records add column if not exists started_at timestamptz;',
    'alter table if exists free_trial_usage_records add column if not exists ends_at timestamptz;',
    'alter table if exists free_trial_usage_records add column if not exists duration_days integer;',
    "alter table if exists free_trial_usage_records add column if not exists policy_snapshot_json jsonb;",
    'alter table if exists free_trial_usage_records add column if not exists created_at timestamptz;',
    "update free_trial_usage_records set policy_snapshot_json = '{}'::jsonb where policy_snapshot_json is null;",
    'update free_trial_usage_records set created_at = now() where created_at is null;',
    'create index if not exists idx_free_trial_usage_records_user_id on free_trial_usage_records (user_id);',
    'create index if not exists idx_free_trial_usage_records_subscription_id on free_trial_usage_records (subscription_id);',
    'create index if not exists idx_free_trial_usage_records_created_at on free_trial_usage_records (created_at);',
    "create table if not exists payment_transfer_settings (id text primary key, bank_name text not null, bank_account_number text not null, bank_account_holder text not null, bank_logo_url text not null default '/bank-logos/generic-bank.svg', usdt_address text not null, usdt_network text not null, updated_by_admin_id text, updated_at timestamptz not null default now());",
    'alter table if exists payment_transfer_settings add column if not exists bank_name text;',
    'alter table if exists payment_transfer_settings add column if not exists bank_account_number text;',
    'alter table if exists payment_transfer_settings add column if not exists bank_account_holder text;',
    "alter table if exists payment_transfer_settings add column if not exists bank_logo_url text;",
    'alter table if exists payment_transfer_settings add column if not exists usdt_address text;',
    'alter table if exists payment_transfer_settings add column if not exists usdt_network text;',
    'alter table if exists payment_transfer_settings add column if not exists updated_by_admin_id text;',
    'alter table if exists payment_transfer_settings add column if not exists updated_at timestamptz;',
    "update payment_transfer_settings set bank_logo_url = '/bank-logos/generic-bank.svg' where bank_logo_url is null or bank_logo_url = '';",
    'create index if not exists idx_payment_transfer_settings_updated_by_admin_id on payment_transfer_settings (updated_by_admin_id);',
    "create table if not exists public_board_posts (id text primary key, category text not null, title text not null, body text not null, is_published boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), updated_by_admin_id text);",
    'alter table if exists public_board_posts add column if not exists category text;',
    'alter table if exists public_board_posts add column if not exists title text;',
    'alter table if exists public_board_posts add column if not exists body text;',
    'alter table if exists public_board_posts add column if not exists is_published boolean;',
    'alter table if exists public_board_posts add column if not exists sort_order integer;',
    'alter table if exists public_board_posts add column if not exists created_at timestamptz;',
    'alter table if exists public_board_posts add column if not exists updated_at timestamptz;',
    'alter table if exists public_board_posts add column if not exists updated_by_admin_id text;',
    "update public_board_posts set is_published = true where is_published is null;",
    'update public_board_posts set sort_order = 0 where sort_order is null;',
    'update public_board_posts set created_at = now() where created_at is null;',
    'update public_board_posts set updated_at = now() where updated_at is null;',
    "insert into public_board_posts (id, category, title, body, is_published, sort_order, created_at, updated_at, updated_by_admin_id) values ('public_board_notice', 'notice', '서비스 운영 공지', '구독 운영, 결제 안내, 차트 접근 정책 변경 사항을 공개 게시판으로 안내합니다.', true, 10, now(), now(), null) on conflict (id) do nothing;",
    "insert into public_board_posts (id, category, title, body, is_published, sort_order, created_at, updated_at, updated_by_admin_id) values ('public_board_qna', 'qna', '공개 질문답변', '자주 반복되는 질문은 공개 답변으로 정리하고, 개인정보가 필요한 내용은 1:1 문의로 처리합니다.', true, 20, now(), now(), null) on conflict (id) do nothing;",
    "insert into public_board_posts (id, category, title, body, is_published, sort_order, created_at, updated_at, updated_by_admin_id) values ('public_board_faq', 'faq', '자주 묻는 질문', '결제, 승인, 무료체험, 시그널 접근 기준을 가장 앞에서 확인할 수 있게 정리합니다.', true, 30, now(), now(), null) on conflict (id) do nothing;",
    'create index if not exists idx_public_board_posts_category on public_board_posts (category);',
    'create index if not exists idx_public_board_posts_is_published on public_board_posts (is_published);',
    'create index if not exists idx_public_board_posts_updated_by_admin_id on public_board_posts (updated_by_admin_id);',
    "create table if not exists notice_popups (id text primary key, title text not null, body_html text not null, is_active boolean not null default true, sort_order integer not null default 0, start_at timestamptz, end_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), updated_by_admin_id text);",
    'alter table if exists notice_popups add column if not exists title text;',
    'alter table if exists notice_popups add column if not exists body_html text;',
    'alter table if exists notice_popups add column if not exists is_active boolean;',
    'alter table if exists notice_popups add column if not exists sort_order integer;',
    'alter table if exists notice_popups add column if not exists start_at timestamptz;',
    'alter table if exists notice_popups add column if not exists end_at timestamptz;',
    'alter table if exists notice_popups add column if not exists created_at timestamptz;',
    'alter table if exists notice_popups add column if not exists updated_at timestamptz;',
    'alter table if exists notice_popups add column if not exists updated_by_admin_id text;',
    'update notice_popups set is_active = true where is_active is null;',
    'update notice_popups set sort_order = 0 where sort_order is null;',
    'update notice_popups set created_at = now() where created_at is null;',
    'update notice_popups set updated_at = now() where updated_at is null;',
    'create index if not exists idx_notice_popups_is_active on notice_popups (is_active);',
    'create index if not exists idx_notice_popups_start_at on notice_popups (start_at);',
    'create index if not exists idx_notice_popups_end_at on notice_popups (end_at);',
    'create index if not exists idx_notice_popups_updated_by_admin_id on notice_popups (updated_by_admin_id);',
    "create table if not exists web_info_settings (id text primary key, terms_content text not null, privacy_content text not null, plan_services_json jsonb not null default '{}'::jsonb, updated_by_admin_id text, updated_at timestamptz not null default now());",
    'alter table if exists web_info_settings add column if not exists terms_content text;',
    'alter table if exists web_info_settings add column if not exists privacy_content text;',
    "alter table if exists web_info_settings add column if not exists plan_services_json jsonb;",
    'alter table if exists web_info_settings add column if not exists updated_by_admin_id text;',
    'alter table if exists web_info_settings add column if not exists updated_at timestamptz;',
    "update web_info_settings set plan_services_json = '{}'::jsonb where plan_services_json is null;",
    "insert into web_info_settings (id, terms_content, privacy_content, updated_at) values ('default', 'TradingCore 서비스 이용약관', 'TradingCore 개인정보보호정책', now()) on conflict (id) do nothing;",
    'create index if not exists idx_web_info_settings_updated_by_admin_id on web_info_settings (updated_by_admin_id);',
    "create table if not exists chart_user_settings (user_id text primary key references users(id), settings_json jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());",
    "alter table if exists chart_user_settings add column if not exists settings_json jsonb;",
    'alter table if exists chart_user_settings add column if not exists updated_at timestamptz;',
    "update chart_user_settings set settings_json = '{}'::jsonb where settings_json is null;",
    'update chart_user_settings set updated_at = now() where updated_at is null;',
    "create table if not exists signal_admin_settings (id text primary key, hidden_symbols_json jsonb not null default '[]'::jsonb, disabled_symbols_json jsonb not null default '[]'::jsonb, hidden_strategy_ids_json jsonb not null default '[]'::jsonb, global_signal_policy_json jsonb not null default '{}'::jsonb, symbol_signal_policies_json jsonb not null default '[]'::jsonb, strategy_param_profiles_json jsonb not null default '[]'::jsonb, strategy_mgmt_visible boolean not null default false, selected_strategy_id text not null default 'strategy_js_grid_martingale', updated_at timestamptz not null default now());",
    "alter table if exists signal_admin_settings add column if not exists hidden_symbols_json jsonb;",
    "alter table if exists signal_admin_settings add column if not exists disabled_symbols_json jsonb;",
    "alter table if exists signal_admin_settings add column if not exists hidden_strategy_ids_json jsonb;",
    "alter table if exists signal_admin_settings add column if not exists global_signal_policy_json jsonb;",
    "alter table if exists signal_admin_settings add column if not exists symbol_signal_policies_json jsonb;",
    "alter table if exists signal_admin_settings add column if not exists strategy_param_profiles_json jsonb;",
    'alter table if exists signal_admin_settings add column if not exists strategy_mgmt_visible boolean;',
    'alter table if exists signal_admin_settings add column if not exists selected_strategy_id text;',
    'alter table if exists signal_admin_settings add column if not exists updated_at timestamptz;',
    "update signal_admin_settings set hidden_symbols_json = '[]'::jsonb where hidden_symbols_json is null;",
    "update signal_admin_settings set disabled_symbols_json = '[]'::jsonb where disabled_symbols_json is null;",
    "update signal_admin_settings set hidden_strategy_ids_json = '[]'::jsonb where hidden_strategy_ids_json is null;",
    "update signal_admin_settings set global_signal_policy_json = '{}'::jsonb where global_signal_policy_json is null;",
    "update signal_admin_settings set symbol_signal_policies_json = '[]'::jsonb where symbol_signal_policies_json is null;",
    "update signal_admin_settings set strategy_param_profiles_json = '[]'::jsonb where strategy_param_profiles_json is null;",
    "update signal_admin_settings set hidden_symbols_json = '[]'::jsonb where jsonb_typeof(hidden_symbols_json) <> 'array';",
    "update signal_admin_settings set disabled_symbols_json = '[]'::jsonb where jsonb_typeof(disabled_symbols_json) <> 'array';",
    "update signal_admin_settings set hidden_strategy_ids_json = '[]'::jsonb where jsonb_typeof(hidden_strategy_ids_json) <> 'array';",
    "update signal_admin_settings set global_signal_policy_json = '{}'::jsonb where jsonb_typeof(global_signal_policy_json) <> 'object';",
    "update signal_admin_settings set symbol_signal_policies_json = '[]'::jsonb where jsonb_typeof(symbol_signal_policies_json) <> 'array';",
    "update signal_admin_settings set strategy_param_profiles_json = '[]'::jsonb where jsonb_typeof(strategy_param_profiles_json) <> 'array';",
    'update signal_admin_settings set strategy_mgmt_visible = false where strategy_mgmt_visible is null;',
    "update signal_admin_settings set selected_strategy_id = 'strategy_js_grid_martingale' where selected_strategy_id is null or selected_strategy_id = '';",
    'update signal_admin_settings set updated_at = now() where updated_at is null;',
    'create table if not exists signup_agreements (id text primary key, user_id text not null, terms_accepted_at timestamptz not null, privacy_accepted_at timestamptz not null, terms_content text not null, privacy_content text not null, terms_settings_updated_at timestamptz not null, privacy_settings_updated_at timestamptz not null, ip_address text, user_agent text, created_at timestamptz not null default now());',
    'alter table if exists signup_agreements add column if not exists user_id text;',
    'alter table if exists signup_agreements add column if not exists terms_accepted_at timestamptz;',
    'alter table if exists signup_agreements add column if not exists privacy_accepted_at timestamptz;',
    'alter table if exists signup_agreements add column if not exists terms_content text;',
    'alter table if exists signup_agreements add column if not exists privacy_content text;',
    'alter table if exists signup_agreements add column if not exists terms_settings_updated_at timestamptz;',
    'alter table if exists signup_agreements add column if not exists privacy_settings_updated_at timestamptz;',
    'alter table if exists signup_agreements add column if not exists ip_address text;',
    'alter table if exists signup_agreements add column if not exists user_agent text;',
    'alter table if exists signup_agreements add column if not exists created_at timestamptz;',
    'create index if not exists idx_signup_agreements_user_id on signup_agreements (user_id);',
    'create index if not exists idx_signup_agreements_created_at on signup_agreements (created_at);',
  ];
}

function renderColumn(name: string, column: DatabaseColumn): string {
  const parts = [`  ${name}`, column.type];
  if (column.primaryKey) parts.push('primary key');
  if (!column.nullable && !column.primaryKey) parts.push('not null');
  if (column.default) parts.push(`default ${column.default}`);
  return parts.join(' ');
}
